language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - python setup.py install
  - pip install -r requirements-dev.txt
  - pip install python-coveralls

# command to run tests
script:
  - py.test --cov ntlm_auth --cov-report term-missing tests

after_success:
  - coveralls

