language: python

python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"

install:
- pip install -U pip setuptools
- pip install .
- pip install -r requirements-test.txt
- pip install python-coveralls

script:
- py.test -v --pep8 --cov ntlm_auth --cov-report term-missing

after_success:
- coveralls
