# Windows Server 2016
image: Visual Studio 2017

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\build-scripts\\run_with_compiler.cmd"
    NTLM_SERVER: 127.0.0.1

  matrix:
  # https://www.appveyor.com/docs/installed-software/#python
  - PYTHON: Python27
  - PYTHON: Python27-x64
  - PYTHON: Python34
  - PYTHON: Python34-x64
  - PYTHON: Python35
  - PYTHON: Python35-x64
  - PYTHON: Python36
  - PYTHON: Python36-x64
  - PYTHON: Python37
  - PYTHON: Python37-x64

services:
- iis

init:
- ps: |
    # Override default Python version/architecture
    $env:Path="C:\$env:PYTHON;C:\$env:PYTHON\Scripts;$env:PATH"
    python -c "import platform; print('Python', platform.python_version(), platform.architecture()[0])"

    $env:NTLM_USERNAME = $($env:USERNAME)
    $env:NTLM_PASSWORD = [Microsoft.Win32.Registry]::GetValue("HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon", "DefaultPassword", '')

install:
- cmd: python -m pip install --upgrade pip
- cmd: pip install --upgrade setuptools
- cmd: pip install -r requirements-test.txt
- cmd: pip install .[cryptography]
- cmd: PowerShell.exe -File appveyor\setup_iis.ps1

build: off

test_script:
- cmd: py.test -v --pep8 --cov ntlm_auth --cov-report term-missing
